### ISSUE TITLE
Safe Exam Browser is not opening even after installing

### ISSUE THREAD

**Issue by d-s-dc** [SafeExamBrowser/seb-server#15]
**Describe the bug**
The application is not running even after proper installation on my windows 10. I have exams on moodle but the application doesn't open after clicking the launch button.

**To Reproduce**
Even the app in my laptop is not opening. No error messages are displayed nor in the installation neither in the running time. It simply doesn't open.

**Expected behavior**
I simply expect the application to run.

**Screenshots**
No error messages are displayed even a single time. I have tried reinstalling many times but still facing the same issue. I have pasted the log report at the end.

**Setup (please complete the following information):**
 - SEB Server Version 3.01
 - Windows 10
 - not opening in chrome
 
**Additional context**
I tries solving the problem with my professors who are conducting the exam but none were able to help so. If possible please help me soon as my exams are going to start within 2 days and I can't attend them until the application starts. The log file report is -
06-09-2020 17:40:11 [Information]: SEB version: 3.0.1.163

06-09-2020 17:40:11 [Information]: Loading the default local client settings

06-09-2020 17:40:11 [Information]: Loading settings from file C:\Users\Dhruv's PC\AppData\Roaming\SafeExamBrowser\SebClientSettings.seb

06-09-2020 17:40:12 [Error]: The .seb file could not be read: 

 Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\Dhruv's PC\AppData\Roaming\SafeExamBrowser\SebClientSettings.seb'.
File name: 'C:\Users\Dhruv's PC\AppData\Roaming\SafeExamBrowser\SebClientSettings.seb'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SebWindowsConfig.SEBSettings.ReadSebConfigurationFile(String fileName, Boolean forEditing, String& filePassword, Boolean& passwordIsHash, X509Certificate2& fileCertificateRef) in C:\Users\appveyor\projects\seb-win-refactoring-l9ysdqd7kes2i06p\SebWindowsConfig\SEBSettings.cs:line 1750 - Could not find file 'C:\Users\Dhruv's PC\AppData\Roaming\SafeExamBrowser\SebClientSettings.seb'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SebWindowsConfig.SEBSettings.ReadSebConfigurationFile(String fileName, Boolean forEditing, String& filePassword, Boolean& passwordIsHash, X509Certificate2& fileCertificateRef) in C:\Users\appveyor\projects\seb-win-refactoring-l9ysdqd7kes2i06p\SebWindowsConfig\SEBSettings.cs:line 1750

06-09-2020 17:40:12 [Information]: OnLoad EventArgs: C:\Program Files\SafeExamBrowser\Configuration\SEBConfigTool.exe

06-09-2020 20:58:50 [Information]: SEB version: 3.0.1.163

06-09-2020 20:58:50 [Information]: Loading the default local client settings

06-09-2020 20:58:50 [Information]: Loading settings from file C:\Users\Dhruv's PC\AppData\Roaming\SafeExamBrowser\SebClientSettings.seb

06-09-2020 20:58:50 [Error]: The .seb file could not be read: 

 Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\Dhruv's PC\AppData\Roaming\SafeExamBrowser\SebClientSettings.seb'.
File name: 'C:\Users\Dhruv's PC\AppData\Roaming\SafeExamBrowser\SebClientSettings.seb'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SebWindowsConfig.SEBSettings.ReadSebConfigurationFile(String fileName, Boolean forEditing, String& filePassword, Boolean& passwordIsHash, X509Certificate2& fileCertificateRef) in C:\Users\appveyor\projects\seb-win-refactoring-l9ysdqd7kes2i06p\SebWindowsConfig\SEBSettings.cs:line 1750 - Could not find file 'C:\Users\Dhruv's PC\AppData\Roaming\SafeExamBrowser\SebClientSettings.seb'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at SebWindowsConfig.SEBSettings.ReadSebConfigurationFile(String fileName, Boolean forEditing, String& filePassword, Boolean& passwordIsHash, X509Certificate2& fileCertificateRef) in C:\Users\appveyor\projects\seb-win-refactoring-l9ysdqd7kes2i06p\SebWindowsConfig\SEBSettings.cs:line 1750

06-09-2020 20:58:50 [Information]: OnLoad EventArgs: C:\Program Files\SafeExamBrowser\Configuration\SEBConfigTool.exe

**Comment by d-s-dc** [comment]
I updated my windows and it seems there are some issues in my windows. I will reopen the issue if the problem persists.
