### ISSUE TITLE
Moodle API connected but Courses arent triggered in LMS lookup 

### ISSUE THREAD

**Issue by TirushV** [SafeExamBrowser/seb-server#37]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - SEB Server Version [e.g. 1.0.0]
 - Setup / IT environment the service is running on
 
**Additional context**
Hi sir, we have deployed SEB server 1.2 version with dockerhub repository (prod/bundled/dockerhub)
also connected Moodle API in LMS setup but here the courses which are in moodle has to be in LMS looksup but it shows empty . Kindly please help us with that
![Screenshot (361)](https://user-images.githubusercontent.com/84138572/131617225-ecdf3b84-08f8-4f51-b3d3-1f5ad75a7a8e.png)
![Screenshot (362)](https://user-images.githubusercontent.com/84138572/131617229-be1aaa0a-949e-4bfe-b065-414bea53372c.png)

**Comment by anhefti** [comment]
Hi, we don't have enough information to analyze the problem. I see two different Moodle based LMSSetups that are active. Are this connections to the same Moodle instance?

1. Please make sure the Moodle is properly setup for webservice Functions and REST API access according to the documentation here: https://seb-server.readthedocs.io/en/latest/lmssetup.html#api-access-account-on-lms (Create Moodle API Access Account)
2. Make also sure that the LMS Setup on SEB Server side is working properly by using the Test action.
3. Make sure the courses on Moodle side are not hidden or closed
4.  If this doesn't help please get the SEB Server logs after clicking on LMS Exam Lookup.

**Comment by TirushV** [comment]
Thanks for the reply sir 
1) & 2) We have followed the documentation and enabled web services on and copied the URL of moodle in LMS setup and it shows successfully connected to API after testing it and activated it.
3) Moodle side the courses are visible.
4) We just created 2 courses to check whether exported Connection configuration is able to connect to the SEB server but here we have issue in LMS lookup now.

**Comment by anhefti** [comment]
Then we need the logs. Ideally from both sides, the SEB Server logs and the Moodle API access logs to find the reason why the courses don't appear in the LMS Exam Lookup. Thanks

**Comment by TirushV** [comment]
at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to call Moodle webservice API function: mod_quiz_get_quizzes_by_courses lms setup: LmsSetup [id=1, institutionId=1, name=Moodle, lmsType=MOODLE, lmsAuthName=era.hostinger, lmsAuthSecret=null, lmsApiUrl=https://moodle.erainterfaces.com/, lmsRestApiToken=null, proxyHost=null, proxyPort=null, proxyAuthUsername=null, proxyAuthSecret=null, active=true] response: {"exception":"invalid_parameter_exception","errorcode":"invalidparameter","message":"Invalid parameter value detected"}
        at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
        at ch.ethz.seb.sebserver.gbl.async.CircuitBreaker.attempt(CircuitBreaker.java:247)
        at ch.ethz.seb.sebserver.gbl.async.CircuitBreaker.handleClosed(CircuitBreaker.java:159)
        ... 25 common frames omitted
Caused by: java.lang.RuntimeException: Failed to call Moodle webservice API function: mod_quiz_get_quizzes_by_courses lms setup: LmsSetup [id=1, institutionId=1, name=Moodle, lmsType=MOODLE, lmsAuthName=era.hostinger, lmsAuthSecret=null, lmsApiUrl=https://moodle.erainterfaces.com/, lmsRestApiToken=null, proxyHost=null, proxyPort=null, proxyAuthUsername=null, proxyAuthSecret=null, active=true] response: {"exception":"invalid_parameter_exception","errorcode":"invalidparameter","message":"Invalid parameter value detected"}
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleRestTemplateFactory$MoodleAPIRestTemplate.callMoodleAPIFunction(MoodleRestTemplateFactory.java:340)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleRestTemplateFactory$MoodleAPIRestTemplate.callMoodleAPIFunction(MoodleRestTemplateFactory.java:281)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseDataAsyncLoader.lambda$callMoodleRestAPI$6(MoodleCourseDataAsyncLoader.java:421)
        ... 11 common frames omitted
04:08:14.949 INFO  [asyncService-6]:[ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseDataAsyncLoader] LMS Setup: 1 loaded 0 courses synchronously
04:08:20.579 INFO  [http-nio-0.0.0.0-8080-exec-7]:[ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleRestTemplateFactory] Successfully get access token from Moodle: LmsSetup [id=1, institutionId=1, name=Moodle, lmsType=MOODLE, lmsAuthName=era.hostinger, lmsAuthSecret=null, lmsApiUrl=https://moodle.erainterfaces.com/, lmsRestApiToken=null, proxyHost=null, proxyPort=null, proxyAuthUsername=null, proxyAuthSecret=null, active=true]
04:08:23.822 INFO  [asyncService-7]:[ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleRestTemplateFactory] Successfully get access token from Moodle: LmsSetup [id=1, institutionId=1, name=Moodle, lmsType=MOODLE, lmsAuthName=era.hostinger, lmsAuthSecret=null, lmsApiUrl=https://moodle.erainterfaces.com/, lmsRestApiToken=null, proxyHost=null, proxyPort=null, proxyAuthUsername=null, proxyAuthSecret=null, active=true]
04:08:24.425 INFO  [asyncService-6]:[ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleRestTemplateFactory] Successfully get access token from Moodle: LmsSetup [id=1, institutionId=1, name=Moodle, lmsType=MOODLE, lmsAuthName=era.hostinger, lmsAuthSecret=null, lmsApiUrl=https://moodle.erainterfaces.com/, lmsRestApiToken=null, proxyHost=null, proxyPort=null, proxyAuthUsername=null, proxyAuthSecret=null, active=true]
04:08:24.635 ERROR [asyncService-5]:[ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseDataAsyncLoader] LMS Setup: 1 Unexpected exception while trying to get course data:
java.lang.RuntimeException: Set CircuitBeaker to half-open state. Cause: java.lang.RuntimeException: Failed to call Moodle webservice API function: mod_quiz_get_quizzes_by_courses lms setup: LmsSetup [id=1, institutionId=1, name=Moodle, lmsType=MOODLE, lmsAuthName=era.hostinger, lmsAuthSecret=null, lmsApiUrl=https://moodle.erainterfaces.com/, lmsRestApiToken=null, proxyHost=null, proxyPort=null, proxyAuthUsername=null, proxyAuthSecret=null, active=true] response: {"exception":"invalid_parameter_exception","errorcode":"invalidparameter","message":"Invalid parameter value detected"}
        at ch.ethz.seb.sebserver.gbl.async.CircuitBreaker.handleClosed(CircuitBreaker.java:178)
        at ch.ethz.seb.sebserver.gbl.async.CircuitBreaker.protectedRun(CircuitBreaker.java:136)
        at ch.ethz.seb.sebserver.gbl.async.CircuitBreaker.handleClosed(CircuitBreaker.java:181)
        at ch.ethz.seb.sebserver.gbl.async.CircuitBreaker.protectedRun(CircuitBreaker.java:136)
        at ch.ethz.seb.sebserver.gbl.async.CircuitBreaker.handleClosed(CircuitBreaker.java:181)
        at ch.ethz.seb.sebserver.gbl.async.CircuitBreaker.protectedRun(CircuitBreaker.java:136)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseDataAsyncLoader.callMoodleRestAPI(MoodleCourseDataAsyncLoader.java:421)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseDataAsyncLoader.getQuizzesBatch(MoodleCourseDataAsyncLoader.java:222)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseDataAsyncLoader.loadAllQuizzes(MoodleCourseDataAsyncLoader.java:193)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseDataAsyncLoader.lambda$loadAndCache$0(MoodleCourseDataAsyncLoader.java:183)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseDataAsyncLoader.loadSync(MoodleCourseDataAsyncLoader.java:147)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseAccess.collectAllQuizzes(MoodleCourseAccess.java:381)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseAccess.lambda$allQuizzesSupplier$12(MoodleCourseAccess.java:308)
        at ch.ethz.seb.sebserver.gbl.util.Result.map(Result.java:229)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseAccess.lambda$allQuizzesSupplier$13(MoodleCourseAccess.java:308)
        at ch.ethz.seb.sebserver.gbl.async.AsyncRunner.runAsync(AsyncRunner.java:31)
        at ch.ethz.seb.sebserver.gbl.async.AsyncRunner$$FastClassBySpringCGLIB$$f147aec0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to call Moodle webservice API function: mod_quiz_get_quizzes_by_courses lms setup: LmsSetup [id=1, institutionId=1, name=Moodle, lmsType=MOODLE, lmsAuthName=era.hostinger, lmsAuthSecret=null, lmsApiUrl=https://moodle.erainterfaces.com/, lmsRestApiToken=null, proxyHost=null, proxyPort=null, proxyAuthUsername=null, proxyAuthSecret=null, active=true] response: {"exception":"invalid_parameter_exception","errorcode":"invalidparameter","message":"Invalid parameter value detected"}
        at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
        at ch.ethz.seb.sebserver.gbl.async.CircuitBreaker.attempt(CircuitBreaker.java:247)
        at ch.ethz.seb.sebserver.gbl.async.CircuitBreaker.handleClosed(CircuitBreaker.java:159)
        ... 25 common frames omitted
Caused by: java.lang.RuntimeException: Failed to call Moodle webservice API function: mod_quiz_get_quizzes_by_courses lms setup: LmsSetup [id=1, institutionId=1, name=Moodle, lmsType=MOODLE, lmsAuthName=era.hostinger, lmsAuthSecret=null, lmsApiUrl=https://moodle.erainterfaces.com/, lmsRestApiToken=null, proxyHost=null, proxyPort=null, proxyAuthUsername=null, proxyAuthSecret=null, active=true] response: {"exception":"invalid_parameter_exception","errorcode":"invalidparameter","message":"Invalid parameter value detected"}
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleRestTemplateFactory$MoodleAPIRestTemplate.callMoodleAPIFunction(MoodleRestTemplateFactory.java:340)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleRestTemplateFactory$MoodleAPIRestTemplate.callMoodleAPIFunction(MoodleRestTemplateFactory.java:281)
        at ch.ethz.seb.sebserver.webservice.servicelayer.lms.impl.moodle.MoodleCourseDataAsyncLoader.lambda$callMoodleRestAPI$6(MoodleCourseDataAsyncLoader.java:421)
        ... 11 common frames omitted

**Comment by anhefti** [comment]
Do you also created quizzes inside the courses? SEB Server mainly looks for quizzes that are used as Exams?

**Comment by TirushV** [comment]
I can give SEB server credentials if u need to check in detail.
Also yes we created quiz inside moodle which SEB takes these as exams.

**Comment by TirushV** [comment]
Sir first we have created Quizzes (2) but it didnt show in exam lookup.
so we have created courses and then inside that we created quiz still its now showing

**Comment by TirushV** [comment]
Sir Is SEB server works with Jitsi meet?, cause we have tried all possible methods to integrate Jitsi meet and SEB with Jitsi meet JWT Token authentication but we are able to see it in SEB server in monitoring section... also even after creating the exam in SEB server after everything configured by Attaching Exam configuration and connection configuration to the exam.
i exported the file and tried it but Client isnt connecting to Server 
![WhatsApp Image 2021-09-01 at 12 19 26 PM](https://user-images.githubusercontent.com/84138572/131627860-84152844-b7aa-42fd-89bc-302ca9d1b811.jpeg)

So after that we made exam file using SEB config tool. After entering the quiz the devices which are connected to the exam or quiz has to be shown in monitoring section thats how jitsi meet work after clicking the townhall option but its not....
Kindly please help us with that.

**Comment by anhefti** [comment]
This is the same question as that about two weeks ago. Please consider that this is an open source project and we are not a service provider. If you need further support to setup your service we recommend to join the [SEB Alliance](https://safeexambrowser.org/alliance/members.html).

To your problem:

Please make sure that SEB Server is properly setup and the needed external access is defined in the docker-compose.yml
![image](https://user-images.githubusercontent.com/39078777/131632890-f657bae7-ce08-4766-9d76-cc2e5327fb72.png)

If this is pointing correctly to your URL where the SEB Server is available form the Internet, and still not working, Please send me the Connection Configuration that you use with SEB (no password protection) so I can have a look if everything is correct with this. If this also doesn't give some hints, please also send us the SEB Client logs.

For the record: The Moodle integration as well as the Jitsi Meet live proctoring integration are not yet finished. The Moodle integration only includes the Course Access feature to import Quizzes as Exams in to SEB Server. The Jitsi Meet integration is still in an experimental state. If you where able to bind a Jitsi Meet service within your imported Exam in SEB Server, it seems to work but you have to need to connect with your SEB Client. Also be aware that you should use the newest SEB Windows Client Version 3.2.

**Comment by TirushV** [comment]
Sir i have update and changed spring directory -> app.properties file to scheme - https, url - domain name, 
also we are able to access our SEB server from the internet and also SEB client logs are empty.
![Screenshot (364)](https://user-images.githubusercontent.com/84138572/131645752-047dbeba-e7bc-4dbd-8fe1-f4d92e49657f.png)

Yes if the client connects to server everything works but that was the issue we were getting even after changing required properties. Also i have changed docker-compose.yml according to the setup which was changed in spring directory file.

**Comment by TirushV** [comment]
[SEBServerSettings.zip](https://github.com/SafeExamBrowser/seb-server/files/7089891/SEBServerSettings.zip)

**Comment by anhefti** [comment]
It appears that you have still the same problem and SEB Server is not correctly setup. In the Connection Configuration file you have sent me is see the URL used to connect to SEB Server is: http://sebnew1.bbbitlf.net:8080. I cannot connect to this address over the Internet. I suppose that the correct URL must be "https://sebnew1.bbbitlf.net"!?

To setup SEB Server properly please do the following:
1. shoud-down the docker container
2. go to the install directory and open the docker-compose.yml file
3. set the corrct values for the URL in the settings:
```
 - sebserver_webservice_http_external_scheme=https
 - sebserver_webservice_http_external_servername=sebnew1.bbbitlf.net
 - sebserver_webservice_http_external_port=
```
4. Save the file and restart the docker container. 
5. Export your Connection Configuration again and try again. 
6. Please also make sure you have trusted TSL Certificates in place.
7. If it is not working, please send me the new Connection Configuration again so I can double-check

**Comment by TirushV** [comment]
sir https://sebnew1.bbbitlf.net is the url this address will work over the internet and also i changed docker-compose.yml file to  required settings still its not able to connect from client to server.
![Screenshot (365)](https://user-images.githubusercontent.com/84138572/131677597-2cd14c48-32d3-434a-b096-87945633a5d9.png)
[SEBServerSettings (1).zip](https://github.com/SafeExamBrowser/seb-server/files/7091306/SEBServerSettings.1.zip)

**Comment by anhefti** [comment]
Okay, the URL now seems to be the right one now. Please make sure you have valid TLS certificate in place. If I connect to the URL with a browser I get:
![image](https://user-images.githubusercontent.com/39078777/131678333-1629813f-27fa-450e-b470-7914b844e4a2.png)

Also please send us the SEB Client Logs that shows the connection errors.

**Comment by TirushV** [comment]
Can u please provide any documentation regarding certificates for this server as the given documentation is unclear.

**Comment by anhefti** [comment]
sorry this was a misunderstanding, we need the SEB Client Logs from the SEB Client application not from the SEB Server. Please find them in the SEB user directory on Windows: \AppData\Local\SafeExamBrowser\Logs

I Have tried myself now and it seems that in fact the invalid TLS certificate is the problem. 
```

2021-09-01 15:31:26.927 [04] - INFO: The configuration was successful.
2021-09-01 15:31:26.931 [04] - INFO: Initializing server...
2021-09-01 15:31:27.496 [04] - DEBUG: [ServerProxy] Request GET 'https://sebnew1.bbbitlf.net/exam-api/discovery' failed due to System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SafeExamBrowser.Server.ServerProxy.TryExecute(HttpMethod method, String url, HttpResponseMessage& response, String content, String contentType, ValueTuple`2[] headers) in C:\Users\appveyor\projects\seb-win-refactoring-3pv4craowibjxry0\SafeExamBrowser.Server\ServerProxy.cs:line 587
2021-09-01 15:31:27.832 [04] - DEBUG: [ServerProxy] Request GET 'https://sebnew1.bbbitlf.net/exam-api/discovery' failed due to System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

You can now either install a valid certificate or try to make the SEB Server accessible over just http, adapt the URL within the SEB Server again and try again.

**Comment by anhefti** [comment]
Sorry, we are not a service providers. For a valid certificate please contact your service provider. This must just be a valid and trusted TLS certificate. Use Letsencrypt (https://letsencrypt.org/) for example.

**Comment by TirushV** [comment]
i have changed it to http and started the containers again to same issue.
Now we will be using TLS certiticate for the server .
Thank you sir

**Comment by anhefti** [comment]
Yes, if you want to work with http instead of https you have to make sure the SEB Server is available within http. This seems not to be the case now (http://sebnew1.bbbitlf.net). It is up to you how secure your setup and service must be and also up to you to set it up properly.

**Comment by TirushV** [comment]
I tried connection configuration with http and https also sir same issue.
Is it because of SSL certificate?

**Comment by anhefti** [comment]
To make it clear:

If you want to run your service within http the SEB Server must be available within http over the Internet. This is now not the case (use http://sebnew1.bbbitlf.net) As long as this is not working, the SEB Client is not able to connect to the SEB Server.
If you want to run your service within https there must be a valid TLS/SSL certificate in place within yor setup (proxy, nginx, ...)

Before using SEB Client just try to connect to your service with a normal Browser (http or https) and check if it works properly.

**Comment by TirushV** [comment]
# New client instance started at 2021-07-21 21:16:21.240

2021-07-21 21:16:21.246 [01] - INFO: Initiating startup procedure...
2021-07-21 21:16:21.265 [01] - INFO: Loading text data...
2021-07-21 21:16:21.267 [01] - DEBUG: [Text] System language is 'en', trying to load data...
2021-07-21 21:16:21.280 [01] - DEBUG: [Text] Data successfully loaded.
2021-07-21 21:16:21.282 [01] - INFO: Initializing runtime connection...
2021-07-21 21:16:21.302 [01] - DEBUG: [RuntimeProxy] Trying to connect to endpoint 'net.pipe://localhost/safeexambrowser/runtime/13e7cccf-5cba-4b08-902c-fd4b7c6ffe1e' with authentication token '6ad808da-6f22-4e34-bd9c-c593fc378c91'...
2021-07-21 21:16:21.475 [01] - DEBUG: [RuntimeProxy] Communication channel is opening...
2021-07-21 21:16:22.093 [01] - DEBUG: [RuntimeProxy] Communication channel has been opened.
2021-07-21 21:16:22.262 [01] - DEBUG: [RuntimeProxy] Connection was established.
2021-07-21 21:16:22.262 [01] - INFO: Successfully connected to the runtime.
2021-07-21 21:16:22.264 [01] - INFO: Initializing application configuration...
2021-07-21 21:16:22.273 [01] - DEBUG: [RuntimeProxy] Sending message 'SimpleMessage -> ConfigurationNeeded'...
2021-07-21 21:16:22.983 [01] - DEBUG: [RuntimeProxy] Received response 'ConfigurationResponse' for message 'SimpleMessage -> ConfigurationNeeded'.
2021-07-21 21:16:22.983 [01] - DEBUG: [RuntimeProxy] Received configuration response.
2021-07-21 21:16:22.983 [01] - INFO: Successfully retrieved the application configuration from the runtime.
2021-07-21 21:16:22.984 [01] - INFO:  -> Client-ID: 9687daab-a3d7-47ce-a661-6f5c164b67b9
2021-07-21 21:16:22.984 [01] - INFO:  -> Runtime-ID: b2c28c1f-d7f3-409f-ae3b-156e4d74306b
2021-07-21 21:16:22.984 [01] - INFO:  -> Session-ID: d122c5a9-c92c-4ae0-95fc-267c223aafc9
2021-07-21 21:16:23.035 [01] - INFO: Starting communication host...
2021-07-21 21:16:23.042 [04] - DEBUG: [ClientHost] Communication host is opening...
2021-07-21 21:16:23.066 [04] - DEBUG: [ClientHost] Communication host has been opened.
2021-07-21 21:16:23.066 [04] - DEBUG: [ClientHost] Successfully started communication host for endpoint 'net.pipe://localhost/safeexambrowser/client/3aae9d81-569e-4957-a20b-9351edb38563'.
2021-07-21 21:16:23.068 [01] - INFO: Starting keyboard interception...
2021-07-21 21:16:23.094 [01] - INFO: Starting mouse interception...
2021-07-21 21:16:23.097 [01] - INFO: Initializing applications...
2021-07-21 21:16:23.389 [01] - DEBUG: [ApplicationMonitor] Initialized 210 currently running processes.
2021-07-21 21:16:23.393 [01] - DEBUG: [ApplicationMonitor] Initialized blacklist with 35 applications: Skype.exe, SkypeApp.exe, SkypeHost.exe, g2mcomm.exe, GotoMeetingWinStore.exe, TeamViewer.exe, vncserver.exe, vncviewer.exe, vncserverui.exe, chromoting.exe, Mikogo-host.exe, AeroAdmin.exe, beamyourscreen-host.exe, RemotePCDesktop.exe, RPCService.exe, RPCSuite.exe, Discord.exe, Camtasia.exe, CamtasiaStudio.exe, Camtasia_Studio.exe, CamPlay.exe, CamRecorder.exe, CamtasiaUtl.exe, slack.exe, Element.exe, Zoom.exe, Telegram.exe, g2mcomm.exe, g2mlauncher.exe, g2mstart.exe, join.me.exe, join.me.sentinel.exe, Teams.exe, webexmta.exe, ptoneclk.exe
2021-07-21 21:16:23.396 [01] - DEBUG: [ApplicationMonitor] Process 'Telegram.exe' (255320) belongs to application 'Telegram.exe' and needs to be terminated.
2021-07-21 21:16:23.399 [01] - DEBUG: [ApplicationMonitor] Initialized whitelist with 0 applications.
2021-07-21 21:16:23.403 [01] - INFO: The following applications need to be terminated: Telegram.exe.
2021-07-21 21:16:29.291 [01] - INFO: The user chose to automatically terminate all running applications.
2021-07-21 21:16:29.293 [01] - DEBUG: [Process 'Telegram.exe' (255320)] Attempting to close process...
2021-07-21 21:16:29.296 [01] - WARNING: [Process 'Telegram.exe' (255320)] Failed to send close message to main window!
2021-07-21 21:16:29.297 [01] - DEBUG: [Process 'Telegram.exe' (255320)] Attempting to close process...
2021-07-21 21:16:29.300 [01] - WARNING: [Process 'Telegram.exe' (255320)] Failed to send close message to main window!
2021-07-21 21:16:29.301 [01] - DEBUG: [Process 'Telegram.exe' (255320)] Attempting to close process...
2021-07-21 21:16:29.304 [01] - WARNING: [Process 'Telegram.exe' (255320)] Failed to send close message to main window!
2021-07-21 21:16:29.305 [01] - DEBUG: [Process 'Telegram.exe' (255320)] Attempting to close process...
2021-07-21 21:16:29.308 [01] - WARNING: [Process 'Telegram.exe' (255320)] Failed to send close message to main window!
2021-07-21 21:16:29.308 [01] - DEBUG: [Process 'Telegram.exe' (255320)] Attempting to close process...
2021-07-21 21:16:29.311 [01] - WARNING: [Process 'Telegram.exe' (255320)] Failed to send close message to main window!
2021-07-21 21:16:29.313 [01] - DEBUG: [Process 'Telegram.exe' (255320)] Attempting to kill process...
2021-07-21 21:16:29.415 [01] - DEBUG: [Process 'Telegram.exe' (255320)] Process has terminated within 500ms.
2021-07-21 21:16:29.416 [01] - INFO: [ApplicationMonitor] Successfully terminated process 'Telegram.exe' (255320).
2021-07-21 21:16:29.416 [01] - INFO: Successfully terminated application 'Telegram.exe'.
2021-07-21 21:16:29.419 [01] - INFO: [ApplicationMonitor] Started monitoring applications.
2021-07-21 21:16:29.422 [01] - INFO: [ApplicationMonitor] Registered system capture start event with ID = 9421b229-1638-49af-af2e-40e61cf82ee7.
2021-07-21 21:16:29.422 [01] - INFO: [ApplicationMonitor] Registered system foreground event with ID = 6c161494-1e18-4c42-865a-d25b5a779f23.
2021-07-21 21:16:29.424 [01] - INFO: Initializing working area...
2021-07-21 21:16:29.425 [01] - INFO: [DisplayMonitor] Disabled sleep mode and display timeout.
2021-07-21 21:16:29.508 [01] - DEBUG: [Taskbar] Calculated physical taskbar height is 50px.
2021-07-21 21:16:29.529 [01] - INFO: [DisplayMonitor] Saved original working area for DISPLAY1 (1920x1080): Left = 0, Top = 0, Right = 1920, Bottom = 1030.
2021-07-21 21:16:29.529 [01] - INFO: [DisplayMonitor] Trying to set new working area for DISPLAY1 (1920x1080): Left = 0, Top = 0, Right = 1920, Bottom = 1030.
2021-07-21 21:16:29.530 [01] - INFO: [DisplayMonitor] Working area of DISPLAY1 (1920x1080) is now set to: Left = 0, Top = 0, Right = 1920, Bottom = 1030.
2021-07-21 21:16:29.531 [01] - INFO: [DisplayMonitor] Started monitoring display changes.
2021-07-21 21:16:29.532 [01] - INFO: Initializing system events...
2021-07-21 21:16:29.590 [01] - INFO: [SystemMonitor] Started monitoring the operating system.
2021-07-21 21:16:29.615 [01] - INFO: Initializing shell...
2021-07-21 21:16:29.741 [01] - INFO: [Audio] Found 'Speakers / Headphones (Realtek Audio)' to be the active audio device.
2021-07-21 21:16:29.964 [01] - INFO: [Audio] Started monitoring the audio device.
2021-07-21 21:16:30.006 [01] - INFO: [Keyboard] Saved current keyboard layout 'English (India)' (ENG).

**Comment by TirushV** [comment]
Sir I tried all possible way to encrypt but the it wasnt getting encrypted also sometimes it shows the container status is in restarting.
Kindly help us with that

**Comment by anhefti** [comment]
Hi, If you want to use TLS/SSL encryption you need to get your own valid and trusted certificates just as you need it for other services. Then if you use the "dockerhub" setup you need to put your SSL certificate Files (.crt and .key) within the confg/nginx/certs directory and remove the localhost.crt and localhost.key files as they are only self signed place-holder certificates. If your certificate files have other names, you can either rename it to localhost or you need to adapt the "app.conf" configuration file to use your certificates. This should work and run then with your valid certificates.

If you want access without TLS/SSL you need to adapt the nginx setup within the docker-compose file. Either remove the nginx proxy service completely and expose the SEB Server directly on the port you need. Or adapt the nginx setup to work with http and expose the needed port within the docker-compose file.

```
reverse-proxy:
    image: "nginx:latest"
    container_name: seb-server-proxy
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/nginx/certs:/sebserver/config/certs
    ports:
      //- 443:443
      -80:80
    networks:
      - seb-server-network
    depends_on:
      - "mariadb"
      - "seb-server"
    restart: unless-stopped

```
```
server {
    listen 80;
    server_name _;
    
	
	location / {
        proxy_pass http://seb-server:8080;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

If this is not working and you have other problems, we need at least some logfiles and some more information about your setup and about what you have tried so far.
